name: publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 20.19.4
          cache: npm
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: dist
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/download-artifact@v5.0.0
        with:
          name: dist
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: client
          clean: true
          clean-exclude: |
            .nojekyll
